= ozil - A man with intelligence and vision image:https://travis-ci.com/theindigamer/ozil.svg?token=atg5zCeDiWzbYpJit3Kx&branch=master[Build Status]
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 2
:sectnums:
:toc: macro
:toclevels: 2
:toc-title:

`ozil` assists you with viewing man/help pages. It is intended as a
porcelain for `man`/`--help` + `less`/`more`/`most`.

toc::[]

## Features

* [X] A top, top qualitee name.
* [ ] Transparently works with man pages and help pages (typically accessed with
  `--help` or `-h`).
  ** [TODO: Insert GIF]
* [ ] Follow links inside man/help pages with hints.
  ** TODO: insert GIF
* [ ] Automatic detection of subcommand help pages.
  ** TODO: insert GIF
* [ ] Simple but flexible configuration with hot-reloading by default.
  ** TODO: insert GIF
* [ ] Search text

## Platforms

Currently, only Linux is supported. Support for other platforms depends
on user contributions. (Note: Windows support is not possible before changes
are made to the Vty package which is a dependency.)

## Installing

### Download a binary

Binaries are unavailable at the moment but I plan on adding them.
See the link:https://github.com/theindigamer/ozil/issues/12[open issue] for this
for current status.

### Building from source

Get link:https://docs.haskellstack.org/en/stable/README/#how-to-install[stack]
first. Then run

```
git clone https://github.com/theindigamer/ozil.git
cd ozil && stack install
```

This will install `ozil` to `~/.local/bin` which is (hopefully?) on your
`$PATH`.

If you wish to use `cabal` instead of `stack`, use `cabal v2-install`
instead of `stack install`. This will install `ozil` to `~/.cabal/bin`.

## Usage

If you want to see the help for `foo`, run `ozil foo`. That's it.
`ozil` will guide you as needed. Of course, you can try using `ozil ozil`
as well :smile:.

### Configuration

TODO: Fill out this section.

## Contributing

See [Contributing.md]().

## Thanks

Special thanks to the Brick maintainer @jtdaugherty for making such as easy to
use and well-documented TUI library. Writing `ozil` wouldn't have been possible
without it :smile:.

## Miscellaneous

### Relation to mandb

- Currently `ozil` depends on `man` for path handling; it doesn't duplicate
  databases or go hunting for files by itself. This may change in the future.

### Non-Goals

- Be a 1-to-1 replacement for `man` or `less`.
